config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  get "about",           to: "pages#about", as: :about
  get "werwirsind",      to: "pages#werwirsind", as: :werwirsind
  get "new",             to: "pages#new", as: :new

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @members =["Till", "Tomasz", "Andre", "Sascha", "Gerdt", "Gordon Gekko", "Bolle", "Jacky Chan"]

  end

  def about
  end

  def werwirsind
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreundlUebern</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Freundliche Übernahme</h1>

app/views/pages/home.html.erb
<img src="./app/assets/images/logo.png" alt="Italian Trulli">


<h1>Willkommen bei FREUNDLICHE ÜBERNAHME</h1>
<h2>Ihrem Partner für Nachfolgeregelungen bei kleinen mittelständischen Unternehmen</h2>
<br><br>
<p>Wir arbeiten hart. Aktuell haben wir den <%=Time.now%></p>

<h3>Unser Team besteht aus langjährigen Experten, die allesamt operative Erfahrung im Mittelstand haben:</h3>

<ol>
  <% @members.each do |member| %>
    <li><%= member %></li>
  <% end %>
</ol>

<h4>Erkunden Sie unsere Seite. Wir haben sie so einfach gehalten, wie wir arbeiten.
    Wir mögen keine komplizieren Lösungen.</h4>
<%= link_to "Wer wir sind", about_path %> <br>
<%= link_to "News", new_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= link_to "Wer wir sind", about_path %>

app/views/pages/werwirsind.html.erb
<h1>Wer wir sind:</h1>

<%= link_to "Startseite", home_path%>
<%= link_to "home", about_path %>